---
- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  when: "'spine' in group_names or 'uplink' in group_names"
  notify: restart frr
  tags:
    - frr

- name: Copy FRR configuration
  template:
    src: spine_frr.j2
    dest: /etc/frr/frr.conf
    backup: yes
  when: "'spine' in group_names or 'uplink' in group_names"
  notify:
    - reload networking
    - reload frr
  tags:
    - frr

- name: Copy interfaces configuration for uplink
  template:
    src: uplink_interfaces.j2
    dest: /etc/network/interfaces
    validate: ifup -a -s -i %s
    backup: yes
  when: "'uplink' in group_names"
  notify: reload networking
  tags:
    - interfaces

- name: Copy interfaces configuration for spines
  template:
    src: spine_interfaces.j2
    dest: /etc/network/interfaces
    validate: ifup -a -s -i %s
    backup: yes
  when: "'spine' in group_names"
  notify: reload networking
  tags:
    - interfaces

- name: Copy interfaces configuration for leafs
  template:
    src: leaf_interfaces.j2
    dest: /etc/network/interfaces
    validate: ifup -a -s -i %s
    backup: yes
  when: "'leaf' in group_names"
  notify: reload networking
  tags:
    - interfaces

- name: Copy PoE configuration
  template:
    src: leaf_poe.j2
    dest: /etc/cumulus/poe.conf
    backup: yes
  when:
    - env == "prod"
    - "'leaf' in group_names"
  notify: load PoE config
  tags:
    - interfaces
