---
- name: restart frr
  service:
    name: frr
    state: restarted

- name: reload frr
  service:
    name: frr
    state: reloaded

- name: reload networking
  command: "ifreload -a"

- name: restart poe
  service:
    name: cumulus-poe
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: restart lldp
  service:
    name: lldp.service
    state: restarted
