---
- name: restart frr
  service:
    name: frr
    state: restarted

- name: reload frr
  service:
    name: frr
    state: reloaded

- name: reload networking
  command: "ifreload -a"

- name: reload poe
  service:
    name: cumulus-poe
    enabled: yes
    state: reloaded
    daemon_reload: yes

- name: reload lldp
  service:
    name: lldpd
    state: reloaded
